import img100 from "../assets/oil.png";
import { FaIndustry, FaShippingFast, FaGraduationCap, FaHospitalAlt, FaHotel } from "react-icons/fa";

export const industries = [
  {
    title: "Oil & Gas Sector",
    title1: "Customized Solution",
    title2: "Pictures for Oil & Gas Sector",
    category: "oil-gas",
    icon: <img src={img100} alt="icon" className="h-10 w-10 object-contain" />,
    features: [
      "Extra heavy duty cabinets to store rigging gears and accessories",
      "Heavy duty rack to organize lifting chains and hooks",
      "Safety cabinets to store corrosives and flammable substances",
      "Extra Heavy duty heavy load bearing assembling workbench",
      "ECB.S Certified battery cabinets to store hazardous lithium ion batteries with charging ports",
      "Dryer racks or cabinets for rigger’s boots and coverall.",
      "Fireman lockers",
      "PPE cabinets – small, medium and large cabinets",
    ],
  },
  {
    title: "Industrial & Manufacturing Sector",
    title1: "Customized Solution",
    title2: "Industrial & Manufacturing Sector",
    category: "industrial",
    icon: <FaIndustry className="text-3xl text-primary" />,
    features: [
      "Extra heavy duty cabinets to store rigging gears and accessories",
      "Heavy duty rack to organize lifting chains and hooks",
      "Safety cabinets to store corrosives and flammable substances",
      "Extra Heavy duty heavy load bearing assembling workbench",
      "ECB.S Certified battery cabinets to store hazardous lithium ion batteries with charging ports",
      "Dryer racks or cabinets for rigger’s boots and coverall.",
      "Fireman lockers",
      "PPE cabinets – small, medium and large cabinets",
    ],
  },
  {
    title: "Logistics & Fulfillment sector",
    title1: "Customized Solution",
    title2: "Logistics & Fulfillment sector",
    category: "oil-gas",
    icon: <FaShippingFast className="text-3xl text-primary" />,
    features: [
      "Extra heavy duty cabinets to store rigging gears and accessories",
      "Heavy duty rack to organize lifting chains and hooks",
      "Safety cabinets to store corrosives and flammable substances",
      "Extra Heavy duty heavy load bearing assembling workbench",
      "ECB.S Certified battery cabinets to store hazardous lithium ion batteries with charging ports",
      "Dryer racks or cabinets for rigger’s boots and coverall.",
      "Fireman lockers",
      "PPE cabinets – small, medium and large cabinets",
    ],
  },
  {
    title: "Hospitality Sector",
    title1: "Customized Solution",
    title2: "Hospitality Sector",
    category: "oil-gas",
    icon: <FaHotel className="text-3xl text-primary" />,
    features: [
      "Extra heavy duty cabinets to store rigging gears and accessories",
      "Heavy duty rack to organize lifting chains and hooks",
      "Safety cabinets to store corrosives and flammable substances",
      "Extra Heavy duty heavy load bearing assembling workbench",
      "ECB.S Certified battery cabinets to store hazardous lithium ion batteries with charging ports",
      "Dryer racks or cabinets for rigger’s boots and coverall.",
      "Fireman lockers",
      "PPE cabinets – small, medium and large cabinets",
    ],
  },
  {
    title: "Educational Sector",
    title1: "Customized Solution",
    title2: "Educational Sector",
    icon: <FaGraduationCap className="text-3xl text-primary" />,
    features: [
      "Extra heavy duty cabinets to store rigging gears and accessories",
      "Heavy duty rack to organize lifting chains and hooks",
      "Safety cabinets to store corrosives and flammable substances",
      "Extra Heavy duty heavy load bearing assembling workbench",
      "ECB.S Certified battery cabinets to store hazardous lithium ion batteries with charging ports",
      "Dryer racks or cabinets for rigger’s boots and coverall.",
      "Fireman lockers",
      "PPE cabinets – small, medium and large cabinets",
    ],
  },
  {
    title: "Health Care Sector",
    title1: "Customized Solution",
    title2: "Health Care Sector",
    icon: <FaHospitalAlt className="text-3xl text-primary" />,
    features: [
      "Extra heavy duty cabinets to store rigging gears and accessories",
      "Heavy duty rack to organize lifting chains and hooks",
      "Safety cabinets to store corrosives and flammable substances",
      "Extra Heavy duty heavy load bearing assembling workbench",
      "ECB.S Certified battery cabinets to store hazardous lithium ion batteries with charging ports",
      "Dryer racks or cabinets for rigger’s boots and coverall.",
      "Fireman lockers",
      "PPE cabinets – small, medium and large cabinets",
    ],
  },
];
