import img100 from "../assets/oil.png";
import { FaIndustry, FaShippingFast, FaGraduationCap, FaHospitalAlt, FaHotel } from "react-icons/fa";

export const industries = [
  {
    title: "Oil & Gas Sector",
    title1: "Customized Solutions",
    title2: "Pictures for Oil & Gas Sector",
    category: "oil-gas",
    icon: <img src={img100} alt="icon" className="h-10 w-10 object-contain" />,
    features: [
      "Extra heavy duty cabinets to store rigging gears and accessories",
      "Heavy duty rack to organize lifting chains and hooks",
      "Safety cabinets to store corrosives and flammable substances",
      "Extra Heavy duty heavy load bearing assembling workbench",
      "ECB.S Certified battery cabinets to store hazardous lithium ion batteries with charging ports",
      "Dryer racks or cabinets for rigger’s boots and coverall",
      "Fireman lockers",
      "PPE cabinets – small, medium and large cabinets",
    ],
  },
  {
    title: "Industrial & Manufacturing Sector",
    title1: "Customized Solutions",
    title2: "Industrial & Manufacturing Sector",
    category: "industrial",
    icon: <FaIndustry className="text-3xl text-primary" />,
    features: [
      "Heavy duty electrical and mechanical workbenches",
      "Tools cabinets – drawer types or cupboard with pegboards",
      "Heavy duty bins cabinets and bin carts",
      "Heavy duty shelf trolleys",
      "CNC tools cabinets",
      "Industrial computer cabinets",
      "Heavy duty stackable pallets",
      "Heavy duty mesh partitions for material storage inside warehouse",
      "Industrial grade factory staff lockers",
      "PPE cabinets – small, medium and large cabinets",
      "Heavy duty Spill trays",
      "Safety storage cabinets – for flammable liquids and corrosives",
      "Fire resistant multi-purpose filing cabinet to store valuable documents and passports",
    ],
  },
  {
    title: "Logistics & Fulfillment Sector",
    title1: "Customized Solutions",
    title2: "Logistics & Fulfillment Sector",
    category: "logistics",
    icon: <FaShippingFast className="text-3xl text-primary" />,
    features: [
      "Heavy duty packing table with carton holders on top",
      "Material handling trolleys with step ladders",
      "Heavy duty platform trolley",
      "Heavy duty mesh trolley",
      "Mesh protection guards for pallet racks",
      "Safety gate for pallets",
      "Medium duty and heavy duty shelving and pallet racks",
      "Bolt free shelving racks and Slotted angle shelving racks",
      "Hardware storage Plastic bins",
      "Heavy duty staff lockers",
      "Safety cabinet to store perfumes and other solvents",
      "Fire resistant cabinet to store valuable documents and passports",
    ],
  },
  {
    title: "Hospitality Sector",
    title1: "Customized Solutions",
    title2: "Hospitality Sector",
    category: "hospitality",
    icon: <FaHotel className="text-3xl text-primary" />,
    features: [
      "Burglary resistant drop safes (night safes) for bars and night clubs",
      "Burglary resistant safes to protect valuables",
      "Fire resistant safes for accounts and stores",
      "Customized Fire resistant filing cabinets with provisions to store passports",
      "Customized Deposit lockers with dual key locking mechanism to protect guest valuables",
      "Customized Heavy duty workbenches for facilities management team",
      "Customized Heavy duty staff lockers – Z shape doors or standard doors",
      "Customized Heavy duty Gym lockers",
      "Customized Stainless steel racks",
      "Customized Stainless steel tables",
      "Customized Stainless steel shelf trolleys and tray trolleys",
      "Customized Clean Linen trolleys and laundry trolleys",
      "Table Trolley",
    ],
  },
  {
    title: "Educational Sector",
    title1: "Customized Solutions",
    title2: "Educational Sector",
    category: "education",
    icon: <FaGraduationCap className="text-3xl text-primary" />,
    features: [
      "Heavy duty vandal resistant student lockers",
      "Low height multi door student lockers",
      "Staff room lockers",
      "Safety cabinet for labs to store acids and flammable substances",
      "Lab cabinets",
      "Heavy duty filing cabinets for accounts and staff rooms",
      "Book trolleys",
      "Heavy duty library racks",
      "Musical instruments storage cabinets",
      "Playground mesh cage rack to store balls and accessories",
      "Laptop lockers with or without charging ports",
      "Wall mountable Cell phone locker with or without charging ports",
    ],
  },
  {
    title: "Health Care Sector",
    title1: "Customized Solutions",
    title2: "Health Care Sector",
    category: "healthcare",
    icon: <FaHospitalAlt className="text-3xl text-primary" />,
    features: [
      "Narcotic cabinet with light and buzzer",
      "Certified dangerous drug storage safe with thermostat feature – Imported",
      "Steel domestic cabinet for cleaning accessories",
      "Safety cabinets to store cleaning chemicals and hazardous substances",
      "Medical cabinets with drawers and glass doors for doctor’s room",
      "Pharmacy cabinet",
      "Staff lockers (available in HPL and Steel options)",
      "Stainless steel treatment trolley – Grade 304 or 316",
      "Equipped medical beds – Imported",
      "Patient transportation carts - Imported",
    ],
  },
];
